import Navbar from '@/components/Navbar'
import './globals.scss'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'

export interface RootLayoutProps {
  children?: React.ReactNode
}

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children } : RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
